---
site:
  title: "CaldeiraG.xyz"
  description: "My personal website"
  profile_image: "https://cdn.caldeirag.xyz/hOli8/hiVEQAvi22.png/raw"
  background_image: "https://cdn.caldeirag.xyz/hOli8/NuRepAde58.jpg/raw"
  footer: "CaldeiraG"

buttons:
  button1:
    platform: "twitter"
    profile: "caldeirag"
    text: "Twitter"
    color: "#1DA1F2"
  button2:
    platform: "github"
    profile: "caldeirag"
    text: "GitHub"
    color: "#24292e"
  button3:
    platform: "twitter"
    profile: "onlytunes_np"
    text: "OnlyTunes"
    color: "#1DA1F2"

---
