---
site:
  title: "CaldeiraG.xyz"
  description: "My personal website"
  profile_image: "https://cdn.caldeirag.xyz/hOli8/hiVEQAvi22.png/raw"
  background_image: "https://cdn.caldeirag.xyz/hOli8/NuRepAde58.jpg/raw"
  footer: "CaldeiraG"

github: CaldeiraG
twitter: CaldeiraGG
kofi: caldeirag
instagram: caldeirag.xyz
discord: CaldeiraG#0496
---
