---
site:
  title: "CaldeiraG.xyz"
  description: "My personal website"
  profile-image: ""

github: CaldeiraG
twitter: CaldeiraGG
kofi: caldeirag
instagram: caldeirag.xyz
discord: CaldeiraG#0496
---
