name : "Feature Request"
description : "Suggest an idea for LibreTree"
labels : [ feature-request ]
body :
  - type : markdown
    attributes :
      value : |
        We appreciate your feedback! Please provide a detailed description of the feature you would like to see.
  - type : textarea
    id : describe-problem
    attributes :
      label : Is your feature request related to a specific problem?
      description : Describe the problem you are trying to solve.
      placeholder : Are you having trouble fulfilling a task?
    validations :
      required : true

  - type : textarea
    id : proposed-solution
    attributes :
      label : What solution would you like to see?
      description : Describe the solution you would want to happen.
      placeholder : With this feature, I would like to be able to...
    validations :
      required : true

  - type : textarea
    id : additional-info
    attributes :
      label : Any additional information?
      description : Anything else you would like to add?
